# This is a basic workflow to help you get started with Actions

name: Code Coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14 LTS
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm test -- --coverage
        env:
          CI: true
      - uses: codecov/codecov-action@v1
        with:
          flags: unittests
          fail_ci_if_error: true
